### ISSUE TITLE
启动不起来啊

### ISSUE THREAD

**Issue by qinghuozhang** [Janche/springboot-security-project#2]
你好，你的启动步骤写的不详细，我点击web模块下的webapplication，启动不成功，显示Could not find artifact com.example.janche:security:jar:0.0.1-SNAPSHOT

**Comment by Janche** [comment]
@qinghuozhang 启动没有问题呀，你看看是不是你的部分依赖没有加载成功，重新maven 一下呢，不行，可以把你的项目打包发给我，我帮你看看，邮箱: lirong_xx@qq.com

**Comment by qinghuozhang** [comment]
好久没看了，您的项目地址再发我一下。。

---原始邮件---
发件人: "弦上的梦"<notifications@github.com&gt;
发送时间: 2021年1月6日(周三) 下午5:45
收件人: "Janche/springboot-security-project"<springboot-security-project@noreply.github.com&gt;;
抄送: "qinghuo"<1584525685@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [Janche/springboot-security-project] 启动不起来啊 (#2)




 
Closed #2.
